FROM php:7.4-fpm

# php.ini setting
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN cd /usr/local/etc \
    && { \
    echo; \
    echo 'date.timezone = Asia/Seoul'; \
    echo; \
    echo '[xDebug]'; \
    echo 'xdebug.remote_enable = 1'; \
    echo 'xdebug.remote_autostart = 1'; \
    echo 'xdebug.remote_port = 9003'; \
    echo 'xdebug.remote_connect_back = on'; \
    echo 'xdebug.idekey = "PHPSTORM"'; \
    } | tee -a php/php.ini

# default application install
RUN apt-get update && apt-get upgrade -y && apt-get install -y wget rdate git unzip

# php ext lib install
RUN apt-get install -y libmemcached-dev zlib1g-dev libicu-dev libgeoip-dev libfreetype6-dev libpng-dev libjpeg-dev libzip-dev libyaml-dev graphviz \
    && pecl install msgpack \
    && pecl install igbinary \
    && pecl install xdebug-2.9.7 \
    && pecl install apcu \
    && pecl install redis \
    && pecl install geoip-1.1.1 \
    && pecl install yaml \
    && pecl install xhprof \
    && pecl install protobuf \
    && docker-php-ext-enable msgpack igbinary xdebug apcu redis geoip opcache yaml xhprof protobuf \
    && docker-php-ext-configure intl \
    && docker-php-ext-install zip intl mysqli pdo_mysql \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

# php ext lib memcached setting
RUN pecl install --onlyreqdeps --nobuild memcached-3.1.3 \
    && cd /tmp/pear/temp/memcached/ \
    && phpize \
    && ./configure --with-php-config=/usr/local/bin/php-config --with-libmemcached-dir=no --with-zlib-dir=no --with-system-fastlz=no --enable-memcached-igbinary=yes --enable-memcached-msgpack=no --enable-memcached-json=no --enable-memcached-protocol=no --enable-memcached-sasl=yes --enable-memcached-session=yes \
    && make \
    && make install \
    && docker-php-ext-enable memcached

# composer install
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# phpunit install
ENV PHPUNIT_PATH="/usr/local/bin/phpunit"
RUN wget -O $PHPUNIT_PATH https://phar.phpunit.de/phpunit-7.phar
RUN chmod +x $PHPUNIT_PATH

EXPOSE 9000
