version: '3.4'

networks:
  lime-network:

services:
  lime-nginx:
    container_name: lime-nginx
    build:
      context: ./config/nginx
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - lime-fpm
    networks:
      - lime-network

  lime-fpm:
    #image: config/php-fpm
    container_name: lime-fpm
    image: php:fpm
    volumes:
      - ../Application:/var/www/html
    networks:
      - lime-network

  # lime-mysql:
  #   image: config/mysql
  #   environment:
  #     - ConnectionString=Server=sqldata;Database=Services.OrderingDb;User Id=sa;Password=[PLACEHOLDER]