version: '3.4'

networks:
  lime-network:

services:
  lime-nginx:
    container_name: lime-nginx
    build:
      context: ./config/nginx
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - lime-fpm
    networks:
      - lime-network
  lime-fpm:
    container_name: lime-fpm
    build:
      context: ./config/fpm
      dockerfile: dockerfile
    volumes:
      - ../Application:/var/www/html
  #  depends_on:
  #    - lime-mysql
    networks:
      - lime-network
  # lime-mysql:
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     #MYSQL_USER: root
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: game
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - ./config/mysql:/docker-entrypoint-initdb.d
  #   networks:
  #     - lime-network