CREATE DATABASE IF NOT EXISTS game;

CREATE TABLE IF NOT EXISTS `TB_USER` (
    `user_id` BIGINT NOT NULL,
    `nickname` VARCHAR(16) NOT NULL,
    `level` INT NOT NULL DEFAULT 1,
    `exp` INT NOT NULL DEFAULT 0,
    `gold` INT NOT NULL DEFAULT 0,
    `update_time` INT NOT NULL DEFAULT 0,
    `insert_time` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`user_id`) USING BTREE
);

INSERT INTO `TB_USER` VALUES (100000, 'dune', 1, 0, 10000, 1622167729, 1622167729);